from powerline_shell.themes.default import DefaultColor

# Xterm 256 color variables
COLOR_WHITE = 15 # white
COLOR_BLACK = 0 # black
COLOR_LIGHT_GREY = 7 # light grey
COLOR_GREY = 8 # grey
COLOR_JOBS = 156 # pale green


COLOR_OK = 2 # green
COLOR_WARN = 221 # Yellow
COLOR_ERROR = 1 # red

class Color(DefaultColor):
    USERNAME_FG = COLOR_GREY
    USERNAME_BG = COLOR_WHITE
    USERNAME_ROOT_BG = COLOR_ERROR

    HOSTNAME_FG = COLOR_GREY
    HOSTNAME_BG = COLOR_LIGHT_GREY

    HOME_SPECIAL_DISPLAY = False
    PATH_BG = COLOR_GREY
    PATH_FG = COLOR_LIGHT_GREY
    CWD_FG = COLOR_WHITE
    SEPARATOR_FG = COLOR_LIGHT_GREY

    READONLY_BG = COLOR_ERROR
    READONLY_FG = COLOR_WHITE

    REPO_CLEAN_BG = COLOR_OK
    REPO_CLEAN_FG = COLOR_BLACK
    REPO_DIRTY_BG = COLOR_WARN
    REPO_DIRTY_FG = COLOR_BLACK

    GIT_AHEAD_BG = COLOR_JOBS
    GIT_AHEAD_FG = COLOR_BLACK
    GIT_BEHIND_BG = GIT_AHEAD_BG
    GIT_BEHIND_FG = GIT_AHEAD_FG
    GIT_STAGED_BG = GIT_AHEAD_BG
    GIT_STAGED_FG = GIT_AHEAD_FG
    GIT_NOTSTAGED_BG = GIT_AHEAD_BG
    GIT_NOTSTAGED_FG = GIT_AHEAD_FG
    GIT_UNTRACKED_BG = COLOR_WARN
    GIT_UNTRACKED_FG = GIT_AHEAD_FG
    GIT_CONFLICTED_BG = COLOR_ERROR
    GIT_CONFLICTED_FG = GIT_AHEAD_FG 

    GIT_STASH_BG = COLOR_JOBS
    GIT_STASH_FG = COLOR_BLACK

    JOBS_FG = COLOR_JOBS
    JOBS_BG = COLOR_GREY

    CMD_PASSED_BG = COLOR_GREY
    CMD_PASSED_FG = COLOR_WHITE
    CMD_FAILED_BG = COLOR_ERROR
    CMD_FAILED_FG = COLOR_BLACK

    SVN_CHANGES_BG = REPO_DIRTY_BG
    SVN_CHANGES_FG = REPO_DIRTY_FG

    VIRTUAL_ENV_BG = COLOR_OK
    VIRTUAL_ENV_FG = COLOR_BLACK

    AWS_PROFILE_FG = COLOR_JOBS
    AWS_PROFILE_BG = COLOR_GREY

    TIME_FG = COLOR_GREY
    TIME_BG = COLOR_LIGHT_GREY
