#!/bin/bash

set -e

echo "Installing Oh My Zsh..."
# RUNZSH=no prevents installer from immediately switching shell and breaking script execution
# --unattended skips prompt for changing default shell automatically
RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"

echo "Cloning plugins..."
git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM}/plugins/zsh-autosuggestions"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting"

echo "Done! Restart your terminal or run: source ~/.zshrc"
