#!/bin/sh
# iget the correct actual monitor names with
# xrandr | awk ' /connected/ { print $1, $2 }'

mon1=eDP-1-1
mon2=HDMI-1-1
TMPBG=/tmp/screen.png
LOCK=$HOME/Pictures/lock.png
RES=$(xrandr | grep 'current' | sed -E 's/.*current\s([0-9]+)\sx\s([0-9]+).*/\1x\2/')
# boxblur=5:1,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2

# Uncomment the sleep command, if you face problems, as a possible workaround
# sleep 3
if xrandr | grep "$mon2 disconnected"; then
  ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK -filter_complex "boxblur=3:1,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 $TMPBG -loglevel quiet
else
  ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK -filter_complex "boxblur=3:1,overlay=(1920-overlay_w)/2:(1080-overlay_h)/2" -vframes 1 $TMPBG -loglevel quiet
fi

i3lock -i $TMPBG -u
rm $TMPBG


