#!/bin/bash
date_icon=""
time_icon=""
date=$(date '+%A %b %d')
date_just_day=$(date '+%d')
time=$(date '+%H:%M')

# echo "$date_icon $date $time_icon $time"
# echo "$date_just_day $time"
echo "<span foreground='#f9e8e0'>$time</span>"
exit 0

